DatingApp/BASE/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='accounts')),
    path('', include('Dating.urls', namespace='dating')),
    path('social-auth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DatingApp/Dating/urls.py
from django.urls import path
from . import views

app_name = 'dating'
urlpatterns = [
    path('profile/', views.UserProfileView.as_view(), name='profile'),
]

DatingApp/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('signup/', views.UserCreateView.as_view(), name='register'),
    path('register-detail/', views.RegisterBasicDetailView.as_view(), name='register_detail'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('employment/', views.EmploymentView.as_view(), name='employment'),
    path('employer-detail/', views.EmployerDetailView.as_view(), name='employer_detail'),
    path('jobseeker/', views.JobSeekerDetailView.as_view(), name='jobseeker'),
    path('relationship/', views.RelationshipView.as_view(), name='relationship'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('home/', views.HomeView.as_view(), name='home'),
]

DatingApp/templates/shared/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"/>

    <link rel="stylesheet" href="{% static 'css/user_create.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <link rel="stylesheet" href="{% static 'css/register.css' %}">
    <link rel="stylesheet" href="{% static 'css/personal_details.css' %}">
    <link rel="stylesheet" href="{% static 'css/employment.css' %}">

    {% block meta %}
        
    {% endblock meta %}

        
</head>
<body>
    
    <main>

        <nav class="navbar navbar-expand-lg navbar-light p-3 shadow">
            <div class="d-flex col-4">
                {% if user.is_authenticated and not request.path == '/register-detail/' %}
                    {% if request.path != '/' and request.path != '/employment/' and request.path != '/signup/' and request.path != '/login/' and request.path != '/employer-detail/' and request.path != '/jobseeker/' and request.path != '/relationship/' %}
                        <div>
                            <button class="nav-opt-btn" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                                <span class="navbar-toggler-icon"></span>
                            </button>
                        </div>
                    {% endif %}
                {% endif %}
                <a class="nav-title navbar-brand" href="#">DatingApp</a>
            </div>
            <!-- <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button> -->

            <div class="col-4">
                {% if user.is_authenticated and not request.path == '/register-detail/' %}
                    {% if request.path != '/' and request.path != '/employment/' and request.path != '/signup/' and request.path != '/login/' and request.path != '/employer-detail/' and request.path != '/jobseeker/' and request.path != '/relationship/' %}
                        <ul class="navbar-nav mx-auto" style="justify-content: space-between; padding-left: 50px; padding-right: 50px;">
                            <li class="nav-item">
                                <a class="nav-link" href="#"><i class="fas fa-house zoom-icon menu-icon" style="font-size: 15px;"></i></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#"><i class="fas fa-compass zoom-icon menu-icon" style="font-size: 15px;"></i></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#"><img class="img-weel img-fluid zoom-icon" src="{% static 'images/color-weel.png' %}"></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#"><i class="fas fa-user-friends zoom-icon menu-icon" style="font-size: 15px;"></i></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="#"><i class="fas fa-comment zoom-icon menu-icon" style="font-size: 15px;"></i></a>
                            </li>
                        </ul>
                    {% endif %}
                {% endif %}
            </div>
          
            <div class="content-section collapse navbar-collapse col-4" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item ">                                  <!--Removed activate class -->
                    {% if user.is_authenticated and not request.path == '/register-detail/' %}
                        {% if request.path != '/' and request.path != '/employment/' and request.path != '/signup/' and request.path != '/login/' and request.path != '/employer-detail/' and request.path != '/jobseeker/' and request.path != '/relationship/' %}
                        <!-- If user is authenticated, show Logout link -->
                            <div class="navbar-items gap-3">
                                <!-- Notifications Icon -->
                                <a href="#" class="nav-icon">
                                    <i class="bell-icon fas fa-bell"></i> <!-- Font Awesome bell icon -->
                                </a>
                        
                                <!-- Profile Image -->
                                <a href="{% url 'dating:profile' %}" class="nav-profile-image">
                                    <img src="{{ user.profile_pic.url }}" class="profile-image"> <!-- Assuming user has a profile image -->
                                </a>
                        
                                <!-- Logout Button -->
                                <form method="post" action="{% url 'accounts:logout' %}" class="logout-form">
                                    {% csrf_token %}
                                    <button type="submit" class="nav-log-btn btn btn-primary">Logout</button>
                                </form>
                            </div>
                        {% endif %}
                    {% else %}
                        <!-- If user is not authenticated, show Login or Signup link -->
                        {% if request.path == '/login/' %}
                            <a class="nav-log-btn btn btn-primary text-white" href="{% url 'accounts:register' %}">Signup</a>
                        {% else %}
                            <a class="nav-log-btn btn btn-primary text-white" href="{% url 'accounts:login' %}">Login</a> 
                        {% endif %}
                    {% endif %}
                </li>
              </ul>
            </div>
        </nav>
        
        {% block content %}
            
        {% endblock content %}
            
    </main>
    
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>

    {% block scripts %}
        
    {% endblock scripts %}
        
</body>
</html>