DatingApp/BASE/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='accounts')),
    path('', include('Dating.urls', namespace='dating')),
    path('social-auth/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

DatingApp/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('signup/', views.UserCreateView.as_view(), name='register'),
    path('register-detail/', views.RegisterBasicDetailView.as_view(), name='register_detail'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('employment/', views.EmploymentView.as_view(), name='employment'),
    path('employer-detail/', views.EmployerDetailView.as_view(), name='employer_detail'),
    path('jobseeker/', views.JobSeekerDetailView.as_view(), name='jobseeker'),
    path('relationship/', views.RelationshipView.as_view(), name='relationship'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('home/', views.HomeView.as_view(), name='home'),
]

DatingApp/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class Hobbies(models.Model):
    id = models.AutoField(primary_key=True)
    hobby = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(unique=True, blank=True, null=True)
    
    
    def __str__(self):
        return self.hobby
    
    
class Interests(models.Model):
    id = models.AutoField(primary_key=True)
    interest = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(unique=True, blank=True, null=True)
    
    
    def __str__(self):
        return self.interest
    
    
class Qualifications(models.Model):
    id = models.AutoField(primary_key=True)
    qualification = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(unique=True, blank=True, null=True)
    
    
    def __str__(self):
        return self.qualification
    
    
class Designation(models.Model):
    id = models.AutoField(primary_key=True)
    designation = models.CharField(max_length=250, unique=True)
    slug = models.SlugField(unique=True, blank=True, null=True)
    
    
    def __str__(self):
        return self.designation
    
    
class User(AbstractUser):
    GENDER_CHOICES = [
        ('M', 'Male'),
        ('F', 'Female'),
    ]
    USER_TYPE_CHOICES = [
        ('employee', 'Employee'),
        ('employer', 'Employer'),
        ('job_seeker', 'Job Seeker'),
    ]
    SKILL_LEVEL_CHOICES = [
        ('beginner', 'Beginner'),
        ('intermediate', 'Intermediate'),
        ('expert', 'Expert'),
    ]
    phone_no = models.CharField(max_length=15, blank=True, null=True)
    age = models.IntegerField(null=True, blank=True)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    dob = models.DateField(null=True, blank=True)
    highest_qualification = models.ForeignKey(to=Qualifications, on_delete=models.CASCADE, null=True)
    hobbies = models.ManyToManyField(to=Hobbies, null=True)
    interest = models.ForeignKey(to=Interests, on_delete=models.CASCADE, null=True)
    smocking_habit = models.BooleanField(default=False)
    drinking_habit = models.BooleanField(default=False)
    profile_pic = models.ImageField(upload_to='profile_pic/', blank=True, null=True)
    company_name = models.CharField(max_length=100, null=True)
    designation = models.ForeignKey(to=Designation, on_delete=models.CASCADE, null=True)
    work_location = models.CharField(max_length=100, null=True)
    skill_level = models.CharField(max_length=20, choices=SKILL_LEVEL_CHOICES)
    slug = models.SlugField(unique=True, blank=True, null=True)
    reels = models.FileField(upload_to='reels/', blank=True, null=True)
    profile_images = models.ManyToManyField('UserProfileImage', blank=True)
    
    
    @property
    def is_employer(self):
        return self.company_name is None and self.designation is None and self.work_location is None

    
class UserProfileImage(models.Model):
    id = models.AutoField(primary_key=True)
    image = models.ImageField(upload_to='profile_images/')
    
    def __str__(self):
        return f"Profile image"
    
    
# class UserHobbies(models.Model):
#     id = models.BigAutoField(primary_key=True)
#     user = models.ForeignKey(to=User)
#     hobby = models.ForeignKey(to=Hobbies)

DatingApp/accounts/forms.py
from django import forms
from accounts.models import User
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import AuthenticationForm
from datetime import date


class UserRegisterForm(forms.ModelForm):
    confirm_password = forms.CharField(max_length=50,min_length=8, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    class Meta:
        model = User
        fields = ['username', 'phone_no', 'email', 'password']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'phone_no': forms.NumberInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'password' : forms.PasswordInput(attrs={'class':'form-control', 'id': 'password'}),
        }
        
        
    def clean_email(self):
        email = self.cleaned_data.get('email')
        
        if not email.endswith('@gmail.com'):
            self.add_error('email',"Email must be a valid Gmail address.")
        if User.objects.filter(email=email).exists():
            self.add_error('email',"A user with that email already exists.")
        return email       
        
    def clean_phone_no(self):
        phone_no = self.cleaned_data.get('phone_no')
        if phone_no and (len(str(phone_no)) != 10 or not phone_no.isdigit()):
            self.add_error('phone_no', "Phone number must be 10 digits.")
        if User.objects.filter(phone_no=phone_no).exists():
            self.add_error('phone_no',"A user with this phone number already exists.")
        return phone_no
        
    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        confirm_password = cleaned_data.get("confirm_password")

        if password and confirm_password and password != confirm_password:
            self.add_error('confirm_password',"Passwords do not match")
        return cleaned_data

        
class UserRegisterDetailForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['age','gender', 'dob', 'highest_qualification', 'hobbies', 'interest', 'smocking_habit',
                  'drinking_habit', 'profile_pic']
        widgets = {
            'age': forms.NumberInput(attrs={'class': 'form-control'}),
            'gender': forms.RadioSelect(choices=User.GENDER_CHOICES),
            'dob': forms.DateInput(attrs={'class': 'form-control', 'type':'date'}),
            'highest_qualification': forms.Select(attrs={'class': 'form-control'}),
            'hobbies': forms.CheckboxSelectMultiple(),
            'interest': forms.Select(attrs={'class': 'form-control'}),
            'smocking_habit': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'drinking_habit': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'profile_pic': forms.FileInput(attrs={'class': 'form-control'}),
        }
        
      
    def clean_age(self):
        age = self.cleaned_data.get('age')
        if age is None:
            return age
        if age < 18:
            self.add_error('age', "Age must be 18 or above.")
        return age

    def clean(self):
        cleaned_data = super().clean()
        age = cleaned_data.get("age")
        dob = cleaned_data.get("dob")

        if dob:
            today = date.today()
            calculated_age = today.year - dob.year - ((today.month, today.day) < (dob.month, dob.day))
            if age != calculated_age:
                self.add_error('age', "Age and date of birth do not match.")
                self.add_error('dob', "Date of birth and age do not match.")

        return cleaned_data
        
        
class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'autofocus': True}))
    password = forms.CharField(label=("Password"), strip=False, widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    
    
class EmploymentForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['company_name', 'designation', 'work_location']
        widgets = {
            'company_name': forms.TextInput(attrs={'class': 'form-control'}),
            'designation': forms.Select(attrs={'class': 'form-control'}),
            'work_location': forms.TextInput(attrs={'class': 'form-control'}),
        }
        
        
class EmploymentJobseekerForm(forms.ModelForm):
    class Meta:
        model = User                            
        fields = ['skill_level']
        widgets = {
            'skill_level': forms.Select(attrs={'class': 'form-control'}),
        }

DatingApp/accounts/views.py
from django.forms import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.views.generic import CreateView,TemplateView,FormView
from django.contrib.auth.views import LoginView,LogoutView
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from .forms import *

# Create your views here.
class HomeView(TemplateView):
    template_name = 'dating/home.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['users'] = User.objects.all()
        return context
    
    
class UserCreateView(CreateView):
    template_name = 'accounts/register.html'
    form_class = UserRegisterForm
    success_url = reverse_lazy('accounts:register_detail')
    
    def form_valid(self, form):
        user = form.save(commit=False)
        user.email = form.cleaned_data['email']
        user.backend = 'django.contrib.auth.backends.ModelBackend'
        user.set_password(user.password)
        user.save()
        login(self.request, user)
        return redirect(self.success_url)
    
    
class RegisterBasicDetailView(LoginRequiredMixin, FormView):
    template_name = 'accounts/register_detail.html'
    form_class = UserRegisterDetailForm
    success_url = reverse_lazy('accounts:employment')
    
    def get_form_kwargs(self):
        return {'instance': self.request.user, 'data': self.request.POST, 'files': self.request.FILES}
    
    
    def get_initial(self) -> dict[str, any]:
        return super().get_initial()
    
    def form_valid(self, form):
        form.save()
        return redirect(self.success_url)
    
    
    
class UserLoginView(LoginView):
    template_name = 'accounts/login.html'
    form_class = LoginForm
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy('accounts:home')
    
    
    
class IndexView(TemplateView):
    template_name = 'accounts/index.html'
    
    
class EmploymentView(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/employment.html'
    
    
class EmployerDetailView(LoginRequiredMixin, FormView):
    template_name = 'accounts/employer.html'
    form_class = EmploymentForm
    success_url = reverse_lazy('accounts:relationship')
    
    def get_form_kwargs(self):
        return {'instance': self.request.user, 'data': self.request.POST}
    
    
    def form_valid(self, form):
        form.save()
        return redirect(self.success_url)
    
    
class JobSeekerDetailView(LoginRequiredMixin, FormView):
    template_name = 'accounts/jobseeker.html'
    form_class = EmploymentJobseekerForm
    success_url = reverse_lazy('accounts:relationship')
    
    def get_form_kwargs(self):
        return {'instance': self.request.user, 'data': self.request.POST}
    
    
    def form_valid(self, form):
        form.save()
        return redirect(self.success_url)
    

class RelationshipView(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/relationship.html'
    
    
class UserLogoutView(LoginRequiredMixin, LogoutView):
    next_page = 'accounts:login'

DatingApp/accounts/templates/accounts/employer.html
{% extends "shared/base.html" %}
{% load static %}
{% block content %}
<div class="container-fluid mt-3">
    <div class="row">   
        <div class="col"></div>
        <div class="col-lg-3 col-md-5 col-sm-6 col-10 mt-5">
            <h1 class='title-sign-up text-center'>Employer/Employee Details</h1>
            <form method="post">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="company_name">{{ form.company_name.label }} :</label>
                    {{ form.company_name }}
                </div>
                <div class="mb-3">
                    <label for="designation">{{ form.designation.label }} :</label>
                    {{ form.designation }}
                </div>
                <div class="mb-3">
                    <label for="work_location">{{ form.work_location.label }} :</label>
                    {{ form.work_location }}
                </div>
                <div class='d-grid mb-5'>
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </form>
                
        </div>
        <div class="col"></div>
    </div>
</div>
{% endblock content %}

DatingApp/accounts/templates/accounts/employment.html
{% extends "shared/base.html" %}
{% load static %}
{% block content %}
<div class="container-fluid mt-3">
    <div class="row">   
        <div class="col"></div>
        <div class="col-lg-3 col-md-5 col-sm-6 col-10 mt-5">
            <h1 class='title-sign-up text-center'>Employment Details</h1>
            
                
            <div class='d-grid mb-5 gap-4'>
                <a href="{% url 'accounts:employer_detail' %}" class="btn btn-primary">Employer/Employee</a>
                <a href="{% url 'accounts:jobseeker' %}" class="btn btn-success">Job Seeker</a>
            </div>
                
        </div>
        <div class="col"></div>
    </div>
</div>
{% endblock content %}

DatingApp/accounts/templates/accounts/index.html
{% extends "shared/base.html" %}
{% load static %}
{% block content %}
<div class="container-fluid">
    <div class="row justify-content-center vh-100">
        <div class="col-12 text-center">
            <div class="bg-img">
                <img class="bg-icon img-fluid" src="{% static 'images/bgimage.png' %}" alt="Background Image">
            </div>
            <p class="text-center mt-2">Let's meet new people around you</p>
            <div class="mt-3">
                <a href="{% url 'accounts:login' %}" class="login-bt btn btn-primary mb-2">Login with Email/Phone</a>
            </div>
            <div>
                <a href="{% url 'social:begin' 'google-oauth2' %}" class="btn btn-primary login-bt">
                    <i class="fab fa-google me-2 google-icon"></i>
                    Login with Google
                </a>
            </div>
            <div>
                <p class="no-account text-dark">Don't have an account? <a href="{% url 'accounts:register' %}" class="signup-link">Sign up</a></p>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

DatingApp/accounts/templates/accounts/jobseeker.html
{% extends "shared/base.html" %}
{% load static %}
{% block content %}
<div class="container-fluid mt-3">
    <div class="row">   
        <div class="col"></div>
        <div class="col-lg-3 col-md-5 col-sm-6 col-10 mt-5">
            <h1 class='title-sign-up text-center'>Employer/Employee Details</h1>
            <form method="post">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="skills">{{ form.skill_level.label }} :</label>
                    {{ form.skill_level }}
                </div>
                <div class='d-grid mb-5'>
                    <button type="submit" class="btn btn-primary">Save</button>
                </div>
            </form>
                
        </div>
        <div class="col"></div>
    </div>
</div>
{% endblock content %}

DatingApp/accounts/templates/accounts/login.html
{% extends "shared/base.html" %}
{% load static %}
{% block content %}
<div class="container-fluid mt-3">
    <div class="row">   
        <div class="col"></div>
        <div class="col-lg-3 col-md-5 col-sm-6 col-10 mt-5">
            <h1 class='text-center'>User Login</h1>
            <form method="post" class="mt-4">
                {% csrf_token %}
                {{ form.as_p }}
                <div class="mb-3">
                    <a class="forgot-pass">Forgot password?</a>
                </div>
                <div class='d-grid mb-3'>
                    <button type="submit" class="btn btn-primary">Login</button>
                </div>
                <p class="no-account">Don't have an account? <a href="{% url 'accounts:register' %}" class="signup-link">Sign up</a></p>
            </form>
        </div>
        <div class="col"></div>
    </div>
</div>
{% endblock content %}

DatingApp/accounts/templates/accounts/register.html
{% extends "shared/base.html" %}
{% load static %}
{% block content %}

<div class="container-fluid">
    <div class="row">   
        <div class="col"></div>
        <div class="col-lg-3 col-md-5 col-sm-6 col-10 mt-2">
            <h1 class='text-center'>Sign Up</h1>
            <form method="post">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="username">{{ form.username.label }} :</label>
                    {{ form.username }}
                </div>
                <div class="mb-3">
                    <label for="phone_no">{{ form.phone_no.label }} :</label>
                    {{ form.phone_no }}
                    {% for error in form.phone_no.errors %}
                        <span class="text-danger">{{ error }}</span>
                    {% endfor %}
                </div>
                <div class="mb-3">
                    <label for="email">{{ form.email.label }} :</label>
                    {{ form.email }}
                    {% for error in form.email.errors %}
                        <span class="text-danger">{{ error }}</span>
                    {% endfor %}
                </div>
                <div class="mb-3">
                    <label for="password">{{ form.password.label }} :</label>
                    {{ form.password }}
                </div>
                <div class="mb-3">
                    <label for="confirm_password">{{ form.confirm_password.label }} :</label>
                    {{ form.confirm_password }}
                    {% for error in form.confirm_password.errors %}
                        <span class="text-danger">{{ error }}</span>
                    {% endfor %}
                </div>
                <div class='d-grid'>
                    <button type="submit" class="btn btn-primary">Signup</button>
                </div>
                <div class='line-text text-dark d-grid text-center mt-3'>OR</div>
                
                <a href="#" class="btn btn-danger d-grid mt-3">Login with Google</a>
                <p class="no-account">Already have an account? <a href="{% url 'accounts:login' %}" class="signup-link">Login</a></p>
            </form>
        </div>
        <div class="col"></div>
    </div>
</div>

{% endblock content %}
<!-- 
{% block scripts %}
<script type="text/javascript">
    $(document).ready(function(){
        $('#datepicker').datepicker({
            format: 'yyyy-mm-dd',
            autoclose: true,
            todayHighlight: true,
            startView: 2, // Start with the decade view
            minViewMode: 0, // Minimum view mode to month
            maxViewMode: 2, // Maximum view mode to decade
            container: '#datepicker', // Ensures the datepicker is appended to the input group
            orientation: "bottom auto", // Ensures the datepicker appears below the input field
        });

        function toggleFields(types) {
            if (types === 'employee' || types === 'employer') {
                $('#company_name').show();
                $('#designation').show();
                $('#location').show();
                $('#skill_level').hide();
            } else if (types === 'job_seeker') {
                $('#company_name').hide();
                $('#designation').hide();
                $('#location').hide();
                $('#skill_level').show();
            } else {
                $('#company_name').hide();
                $('#designation').hide();
                $('#location').hide();
                $('#skill_level').hide();
            }
        }

        // Initialize fields based on the current type value
        toggleFields($('#id_type select[name="types"]').val());

        $('#id_type select[name="types"]').change(function() {
            toggleFields($(this).val());
        });
    });
</script>
{% endblock scripts %} -->

DatingApp/accounts/templates/accounts/register_detail.html
{% extends "shared/base.html" %}
{% load static %}
{% block content %}
<div class="container-fluid mt-3">
    <div class="row">   
        <div class="col"></div>
        <div class="col-lg-3 col-md-5 col-sm-6 col-10 mt-5">
            <h1 class='title-sign-up text-center'>User Details Registration</h1>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="age">{{ form.age.label }} :</label>
                    {{ form.age }}
                    {% for error in form.age.errors %}
                        <span class="text-danger">{{ error }}</span>
                    {% endfor %}
                </div>
                <div class="mb-3">
                    <label for="gender">{{ form.gender.label }} :</label>
                    {{ form.gender }}
                </div>
                <div class="mb-3">
                    <label for="dob">{{ form.dob.label }} :</label>
                    {{ form.dob }}
                    {% for error in form.dob.errors %}
                        <span class="text-danger">{{ error }}</span>
                    {% endfor %}
                </div>
                <div class="mb-3">
                    <label for="highest_qualification">{{ form.highest_qualification.label }} :</label>
                    {{ form.highest_qualification }}
                </div>
                <div class="mb-3">
                    <label for="hobbies">{{ form.hobbies.label }} :</label>
                    {{ form.hobbies }}
                </div>
                <div class="mb-3">
                    <label for="interest">{{ form.interest.label }} :</label>
                    {{ form.interest }}
                </div>
                <div class="mb-3">
                    <label for="smocking_habit">{{ form.smocking_habit.label }} :</label>
                    {{ form.smocking_habit }}
                </div>
                <div class="mb-3">
                    <label for="drinking_habit">{{ form.drinking_habit.label }} :</label>
                    {{ form.drinking_habit }}
                </div>
                <div class="mb-3">
                    <label for="profile_pic">{{ form.profile_pic.label }} :</label>
                    {{ form.profile_pic }}
                </div>
                <div class='d-grid mb-5'>
                    <button type="submit" class="btn btn-primary">Save</button>
                
                </div>
            </form>
        </div>
        <div class="col"></div>
    </div>
</div>
{% endblock content %}
{% block scripts %}
<script>
    // Set maximum date for the date picker to ensure user is at least 18 years old
    document.addEventListener('DOMContentLoaded', function() {
        var today = new Date();
        var minDate = new Date(today.getFullYear() - 100, today.getMonth(), today.getDate());
        var maxDate = new Date(today.getFullYear() - 18, today.getMonth(), today.getDate());
        var dobField = document.querySelector('input[name="dob"]');

        if (dobField) {
            dobField.setAttribute('max', formatDate(maxDate));
            dobField.setAttribute('min', formatDate(minDate));
        }

        function formatDate(date) {
            var day = ("0" + date.getDate()).slice(-2);
            var month = ("0" + (date.getMonth() + 1)).slice(-2);
            var year = date.getFullYear();
            return year + "-" + month + "-" + day;
        }
    });
</script>
{% endblock scripts %}

DatingApp/accounts/templates/accounts/relationship.html
{% extends "shared/base.html" %}
{% load static %}
{% block content %}
    <div class="container-fluid mt-7">
        <div class="row mb-5">
            <div class="col"></div>
            <div class="col-3 mt-3">
                <h1 class='title-detail text-center' style="color: #2b0238;">Choose One</h1>
                <div class='d-grid gap-2'>
                    <a href="{% url 'accounts:home' %}" class="btn btn-warning">Short Term Relationship</a>
                    <a href="#" class="btn btn-primary">Long Term Relationship</a>
                </div>
            </div>
            <div class="col"></div>
        </div>
    </div>
{% endblock content %}